sudo: required
services:
  - docker

before_install:
  - docker build -t amanuelggy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amanuelggy/docker-react npm run test -- --coverage